.TH CALYPSO "1" "August 2013" "calypso 1.1" "User Commands"
.SH NAME
calypso \- CalDAV/CardDAV server with git storage
.SH SYNOPSIS
.B calypso
[\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
show version and exit
.TP
\fB\-d\fR, \fB\-\-daemon\fR
launch as daemon
.TP
\fB\-f\fR, \fB\-\-foreground\fR
launch in foreground (opposite of \fB\-\-daemon\fR)
.TP
\fB\-H\fR HOST, \fB\-\-host\fR=\fIHOST\fR
set server hostname
.TP
\fB\-p\fR PORT, \fB\-\-port\fR=\fIPORT\fR
set server port
.TP
\fB\-s\fR, \fB\-\-ssl\fR
use SSL connection
.TP
\fB\-S\fR, \fB\-\-no\-ssl\fR
do not use SSL connection (opposite of \fB\-\-ssl\fR)
.TP
\fB\-k\fR KEY, \fB\-\-key\fR=\fIKEY\fR
private key file
.TP
\fB\-c\fR CERTIFICATE, \fB\-\-certificate\fR=\fICERTIFICATE\fR
certificate file
.HP
\fB\-i\fR IMPORT_DEST, \fB\-\-import\fR=\fIIMPORT_DEST\fR
.TP
\fB\-g\fR, \fB\-\-debug\fR
enable debug logging
.SH AUTHOR
Written by Keith Packard <keithp@keithp.com>
.SH COPYRIGHT
Copyright © 2011 Keith Packard
.br
Copyright © 2008-2011 Guillaume Ayoub
.br
Copyright © 2008 Nicolas Kandel
.br
Copyright © 2008 Pascal Halter
.br
.P
This library is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
.P
This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.P
You should have received a copy of the GNU General Public License
along with Calypso.  If not, see <http://www.gnu.org/licenses/>.
